app-academy_goals-app-master/config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern            Controller#Action
#       users POST   /users(.:format)       users#create
#    new_user GET    /users/new(.:format)   users#new
#       goals GET    /goals(.:format)       goals#index
#             POST   /goals(.:format)       goals#create
#    new_goal GET    /goals/new(.:format)   goals#new
#        goal GET    /goals/:id(.:format)   goals#show
#     session POST   /session(.:format)     sessions#create
# new_session GET    /session/new(.:format) sessions#new
#             DELETE /session(.:format)     sessions#destroy
#

Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :goals do
    member do
      post "complete"
      post "incomplete"
    end
  end

  resource :session, only: [:new, :create, :destroy]
end

app-academy_goals-app-master/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id                :integer          not null, primary key
#  user_id           :integer          not null
#  content           :text             not null
#  completion_status :boolean          default(FALSE), not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  visibility_status :string           default("PUBLIC")
#

class Goal < ActiveRecord::Base
  V_STAT = %w( PUBLIC PRIVATE )

  validates :user_id, :content, :visibility_status, presence: true
  validates :visibility_status, inclusion: V_STAT

  belongs_to :user
end

app-academy_goals-app-master/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :goals

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return if user.nil?
    return user if user.is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def private_goals
    goals.where(visibility_status: "PRIVATE")
  end

  def public_goals
    goals.where(visibility_status: "PUBLIC")
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password.to_s
    self.password_digest = BCrypt::Password.create(password).to_s
    @password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password.to_s)
  end

    private

    def ensure_session_token
      self.session_token ||= User.generate_session_token
    end

end

app-academy_goals-app-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  private

  def ensure_logged_in
    
  end
end

app-academy_goals-app-master/app/controllers/goals_controller.rb
# == Schema Information
#
# Table name: goals
#
#  id                :integer          not null, primary key
#  user_id           :integer          not null
#  content           :text             not null
#  completion_status :boolean          default(FALSE), not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  visibility_status :string           default("PUBLIC")
#

class GoalsController < ApplicationController

  before_action :ensure_user_is_author, only: [:edit, :update, :destroy, :complete, :incomplete]
  def new
    @goal = Goal.new
  end

  def index
    @goals = Goal.all
  end

  def show
    @goal = Goal.find_by(id: params[:id])
  end

  def edit
    @goal = Goal.find_by(id: params[:id])
  end

  def update
    @goal = Goal.find_by(id: params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      @goal = Goal.new(goal_params)
      render :edit
    end
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def complete
    @goal = Goal.find_by(id: params[:id])
    @goal.completion_status = true
    @goal.save!
    redirect_to goal_url(@goal)
  end

  def incomplete
    @goal = Goal.find_by(id: params[:id])
    @goal.completion_status = false
    @goal.save!
    redirect_to goal_url(@goal)
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_url(@goal.user)
  end

    private

    def goal_params
      params.require(:goal).permit(:content, :visibility_status, :completion_status)
    end

    def ensure_user_is_author
      @goal = Goal.find(params[:id])
      return if @goal.user == current_user
      flash[:errors] = ["forbidden"]
      redirect_to goals_url
    end
end

app-academy_goals-app-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(*user_params.values)
    if @user
      login_user!(@user)
      redirect_to goals_url
    else
      @user = User.new(user_params)
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app-academy_goals-app-master/app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app-academy_goals-app-master/app/helpers/application_helper.rb
module ApplicationHelper

  def csrf_token
    html =  <<-HTML
      <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">
    HTML

    html.html_safe
  end

end

app-academy_goals-app-master/app/helpers/goals_helper.rb
# == Schema Information
#
# Table name: goals
#
#  id                :integer          not null, primary key
#  user_id           :integer          not null
#  content           :text             not null
#  completion_status :boolean          default(FALSE), not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  visibility_status :string           default("PUBLIC")
#

module GoalsHelper
end

app-academy_goals-app-master/app/helpers/sessions_helper.rb
module SessionsHelper
end

app-academy_goals-app-master/app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

module UsersHelper
end

app-academy_goals-app-master/app/views/goals/_form.html.erb
<% method_type = goal.persisted? ? :patch : :post %>
<% action_type = goal.persisted? ? goal_url(goal) : goals_url %>
<% message = goal.persisted? ? "Change my dream!" : "Come True" %>

<form action="<%= action_type %>" method="post">
  <input type="hidden" name="_method" value="<%= method_type %>">
  <%= csrf_token %>


  <label for="content">Content:</label>
  <br/>
  <textarea name="goal[content]"
            id="content"
            rows="8"
            cols="60"><%= goal.content %></textarea>
  <br/>
  <br/>
  <% Goal::V_STAT.each do |status| %>
  <label for="<%= status %>"><%= status.capitalize %></label>
    <input
      name="goal[visibility_status]"
      id="<%= status %>"
      type="radio"
      value="<%= status %>"
      <%= "checked" if goal.visibility_status == status %>>
  <% end %>

  <p><input type="submit" value="<%= message %>"></p>

</form>

app-academy_goals-app-master/app/views/goals/_goal.html.erb
<% if goal.completion_status %>
  <% button = button_to "Just Kidding...", incomplete_goal_url(goal), method: :post %>
<% else %>
  <% button = button_to "Realized Dream", complete_goal_url(goal), method: :post %>
<% end %>

<h2> Your Dream </h2>

<% if goal.completion_status %>
<h3>Completed Your Dream!</h3>
<% end %>

<p> <%=goal.content%> </p>

<div border-width="1px" >
  <h2> Your Options: </h2>
  <table>
    <tr>
      <td> <%= button %> </td>
      <td> <%= link_to "Change your dream", edit_goal_url(goal) %> </td>
      <td> <%= button_to "Face Reality", goal_url(goal), method: :delete %> </td>
      <td> <%= goal.visibility_status.capitalize %> </td>
    </tr>
  </table>


</div>

app-academy_goals-app-master/app/views/goals/edit.html.erb
<h1> I had a change of heart.... </h1>

<%= render "form", goal: @goal %>

app-academy_goals-app-master/app/views/goals/index.html.erb
<h1>Goal Index</h1>
<p>Find me in app/views/goals/index.html.erb</p>

app-academy_goals-app-master/app/views/goals/new.html.erb
<h1>Make your Dream!</h1>

<%= render "goals/form", goal: @goal %>

app-academy_goals-app-master/app/views/goals/show.html.erb
<h1>GOAL</h1>

<%= render "goals/goal", goal: @goal %>

app-academy_goals-app-master/app/views/users/new.html.erb
<h1>Make your dreams come true!</h1>

<form action="<%= users_url %>" method="post">
  <%= csrf_token %>
  <label for="username">Username:</label>
  <br/>
  <input type="text"
         name="user[username]"
         value="<%= @user.username %>"
         id="username">
  <br/>
  <label for="password">Password:</label>
  <br/>
  <input type="password"
         name="user[password]"
         value=""
         id="password">
   <br/>
   <input type="submit" value="Dream On!">
</form>

app-academy_goals-app-master/app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>

<h2> Your goals: </h2>

<%= render @user.public_goals %>
<%= render @user.private_goals if @user == current_user %>